### ISSUE TITLE
Versioned URL document

### ISSUE THREAD

**Issue by sevkioruc** [galatajs/http#26]
Hey @ssibrahimbas , 
Versioned urls document contains this comment line `http://localhost:3000/product/v2/123`
Can it be like this  `http://localhost:3000/v2/product/123` ?

**Comment by ssibrahimbas** [comment]
For versioning, the version must be in a subdomain. For example, if there is a versioning for products, it should be `products/v1` or `products/v2`.

But this can be solved with a global router. For example, you can get the result you want with a code like this:

```ts
import { createRouter, Request, Response } from "@galatajs/http"

const v2Router = createRouter({ prefix: 'v2', onlyVersion: true })

const productRouter = createRouter({ prefix: 'products' })
v2Router.use(productRouter)

productRouter.get(':id', (req: Request, res: Response) => {
  return res.success(`get product for: #${req.params.id}`)
})

// http://localhost:3000/v2/products/123
```

**Comment by scuro-dev** [comment]
@ssibrahimbas  Thank you for your clarification. I will research on this topic.
